name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: Install Newman
      displayName: DISPLAY NAME
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: Run Regression Tests
      displayName: DISPLAY NAME
      continueOnError: true
      inputs:
        script: 'newman run ./7.automated-testing-task/StarterAPIs.json'
        workingDirectory: 'starter-code/automatedtesting/postman'